### ISSUE TITLE
StravaData.Athlete function

### ISSUE THREAD

**Issue by FrankFromGermany** [Kjonge/PowerBIStravaConnector#1]
Line 129 of Strava.pq 
tableresult = Record.ToTable(ConvertToTable)
ConvertToTable is a table not a record !?
Does this work?
Unfortunately, I cannot test the function.

**Comment by Kjonge** [comment]
it does, it is a bit confusing I agree

**Comment by FrankFromGermany** [comment]
After testing, this function does NOT work. Fortunately, it will never be called as the json returned will always be a record.

StravaData.Athlete = (json) =>
    let
        ConvertToTable = Table.FromList(json, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
        tableresult = Record.ToTable(ConvertToTable),
        result = Table.Pivot(tableresult, List.Distinct(tableresult[Name]), "Name", "Value")
in
   result;
