### ISSUE TITLE
Connector stopped working after Power BI update

### ISSUE THREAD

**Issue by ViktorRyz** [Kjonge/PowerBIStravaConnector#5]
It stops working. Power BI doesn’t see your custom connector. Do you have any ideas?
Best regards, Viktor

**Comment by migueesc123** [comment]
@ruthpozuelo

**Comment by Sonneke** [comment]
This worked for me:
Try renaming the Strava.pq file and the Strava.query.pq file to Strava.m and Strava.query.m Also check the program folder that there are no .pq files anymore. Rebuild the solution and copy the new .mez file to Microsoft Power BI Desktop\Custom Connectors.
I also loaded the latest Power Query SDK into Visual Studio but I'm not sure if that is necessary.

**Comment by khha** [comment]
@Sonneke I try this but it didnt work. I renamed the 2 files. I installed the latest version of Power Query SDK and the latest version of Power BI Desktop. I add the new mez file in : C:\Users\myusername\OneDrive\Documents\Power BI Desktop\Custom Connectors

**Comment by Kjonge** [comment]
Correct it should be [My Documents]\Power BI Desktop\Custom Connectors. https://github.com/Microsoft/DataConnectors
