### ISSUE TITLE
Receive another issue after update

### ISSUE THREAD

**Issue by khha** [Kjonge/PowerBIStravaConnector#6]
@Kjonge  I downloaded today the latest version of the PowerBI Strava connector. I can see and select the connector in Power BI desktop. I click on "Connect to Strava". I clicked on "Sign in" and see an IE popup to this url: https://www.strava.com/oauth/authorize. In the popup I see an error:

HTTP 400 Bad Request

**Comment by Kjonge** [comment]
I can't repro this :( any more details?
