### ISSUE TITLE
microsoft.mashup....exception

### ISSUE THREAD

**Issue by TheFlyingBadger** [Kjonge/PowerBIStravaConnector#7]
I'm getting a microsoft mashup exception, when tracking it back through Fiddler strava.com seems to be throwing a 401 exception at me. Any ideas?

**Comment by Kjonge** [comment]
I have seen this before when the callback URL's are not set right in the strava app. check out the settings here: https://www.kasperonbi.com/building-the-power-bi-strava-data-connector

**Comment by Kjonge** [comment]
cannot be reproed
