### ISSUE TITLE
Connector has stopped working

### ISSUE THREAD

**Issue by CincyTriGuy** [Kjonge/PowerBIStravaConnector#8]
I've been using this successfully since November 2017. In late July 2018 it stopped working. When I try to refresh I'm now getting an Activities error "The import Strava.Contents matches no exports. Did you miss a module reference?" as well as an Athlete error "Load was cancelled by an error in loading a previous table".

**Comment by Kjonge** [comment]
try rebuilding the connector. It still works for me and others.
